name: 'Update feedback labels on comment'
on: 'issue_comment'

jobs:
  feedback:
    runs-on: ubuntu-latest
    steps:
    - name: Echo github obj
      if: github.event.issue && github.event.issue.labels
      run: echo "${{ toJson(github.event.issue.labels) }}"
